In [2]:
import numpy as np

# Step2 aとbの行列を格納する多次元配列のコードを記述する
a = np.array([[0,1],[2,3],[4,5]])
b = np.array([[0,1,2,3],[4,5,6,7]])

# Step3 行列の積の計算をするコードを記述する
result = np.dot(a, b)

# Step4 計算結果を表示するコードを記述する
print("行列の積の結果")
print(result)

# Step5 行列の要素の最大値を求めるコードを記述する
print("最大値")
print(result.max())

行列の積の結果
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値
47
